//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekos
{
    using System;
    using System.Collections.Generic;
    
    public partial class hizliNotSistemi
    {
        public int Id { get; set; }
        public Nullable<int> personelId { get; set; }
        public string notBaslik { get; set; }
        public string notIcerik { get; set; }
        public Nullable<bool> yerineGetirildiMi { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
