//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekos
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitapAlanOgrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KitapAlanOgrenci()
        {
            this.SmsGecmisi = new HashSet<SmsGecmisi>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OgrId { get; set; }
        public Nullable<int> KitapId { get; set; }
        public Nullable<System.DateTime> AlisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<bool> HasarliTeslim { get; set; }
        public Nullable<int> GecenGunSayisi { get; set; }
        public Nullable<int> geciktirmeGunSayisi { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmsGecmisi> SmsGecmisi { get; set; }
    }
}
