//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ekosEntities : DbContext
    {
        public ekosEntities()
            : base("name=ekosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolumler> Bolumler { get; set; }
        public virtual DbSet<CokAratilanKitaplar> CokAratilanKitaplar { get; set; }
        public virtual DbSet<hizliNotSistemi> hizliNotSistemi { get; set; }
        public virtual DbSet<KitapAlanOgrenci> KitapAlanOgrenci { get; set; }
        public virtual DbSet<KitapKategori> KitapKategori { get; set; }
        public virtual DbSet<Kitaplar> Kitaplar { get; set; }
        public virtual DbSet<KitapNotlar> KitapNotlar { get; set; }
        public virtual DbSet<KodHataListesi> KodHataListesi { get; set; }
        public virtual DbSet<Ogrenciler> Ogrenciler { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<PersonelBeniHatirla> PersonelBeniHatirla { get; set; }
        public virtual DbSet<PersonelHataliGiris> PersonelHataliGiris { get; set; }
        public virtual DbSet<PersonelLogKaydi> PersonelLogKaydi { get; set; }
        public virtual DbSet<PersonelSifre> PersonelSifre { get; set; }
        public virtual DbSet<SmsGecmisi> SmsGecmisi { get; set; }
        public virtual DbSet<TalepEdilenKitaplar> TalepEdilenKitaplar { get; set; }
        public virtual DbSet<YardimMerkezi> YardimMerkezi { get; set; }
        public virtual DbSet<Yayinevi> Yayinevi { get; set; }
        public virtual DbSet<Yazarlar> Yazarlar { get; set; }
    }
}
