//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.KitapAlanOgrenci = new HashSet<KitapAlanOgrenci>();
        }
    
        public int Id { get; set; }
        public string OgrNo { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public string OgrTel { get; set; }
        public string OgrEposta { get; set; }
        public Nullable<int> BolumId { get; set; }
        public Nullable<int> SinifNo { get; set; }
        public Nullable<bool> MezunMu { get; set; }
        public Nullable<bool> DisiplinCezali { get; set; }
        public Nullable<bool> KutuphaneBlok { get; set; }
        public Nullable<byte> KitapAlmaSayisi { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapAlanOgrenci> KitapAlanOgrenci { get; set; }
    }
}
